### ISSUE TITLE
/learn/state ends abruptly

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersandjs.com#102]
Went back to the original commit, it's always been like that so I have no idea what it was supposed to say

http://cl.ly/image/1G1n3b0c3Q00

**Comment by kamilogorek** [comment]
We can rephrase it, but are we sure that `isState` should return `true` for everything that's based on it? Models, collections, views?

**Comment by HenrikJoreteg** [comment]
@kamilogorek I think it should, yes because it is. Same idea as inheritance when you do `instanceof` checks. For example, any backbone model still passes `instanceof Backbone.Model` checks.

**Comment by e2jk** [comment]
As a new user, I am confused by that last sentence as well. It reads like "since the same constructor isn't used, instanceof will fail, so we created a new boolean which returns true". No clue how to use that, let alone how it works.

**Comment by kamilogorek** [comment]
@e2jk I believe that latter sentence explains this, and that's why it starts with:

> In order to deal with this...

**Comment by gsf** [comment]
Just noticed this as well. Would be great to have some clarification of isState and complete the thought there. Don't leave me hanging! :hand:

**Comment by HenrikJoreteg** [comment]
Fixed and added an example.
