### ISSUE TITLE
Docs pages: nav and scrolling not working in Safari

### ISSUE THREAD

**Issue by lynnandtonic** [AmpersandJS/ampersandjs.com#119]
Per https://twitter.com/simmelj/status/544911599761649665

In Safari, the docs navigation is freezing/unscrollable at times. This is happening at ampersandjs.com/docs and amp.ampersandjs.com.

**Comment by lynnandtonic** [comment]
I tried adjusting z-index and changing the positions of the nav and docs sections so they don't overlap at all. Neither seemed to solve the problem. Will keep looking.

**Comment by lynnandtonic** [comment]
I tried putting a child element inside the fixed-position nav and putting the overflow on the child. Did not work. Still looking.

**Comment by lynnandtonic** [comment]
So this is a bug in Safari that happens with position-fixed even when there is basically no other CSS or JS loaded. As far as I can tell, we have three options:
1. Do nothing and wait for this bug to be fixed.
2. Make the navigation not fixed (scroll simultaneously with the content).
3. Redesign the docs pages a bit to allow for independent scrolling of the navigation and content. (From my testing, it seems that _both_ sections being fixed works for some reason. This would mostly change the way the top nav works.)

Any thoughts or better ideas?

**Comment by adamavenir** [comment]
Can we do a custom targeted stylesheet for Safari that fixes this temporarily? Then whichever option you think best for the scenario. :)

**Comment by lynnandtonic** [comment]
Ah! I did not think to do that. :)

Is this a reasonable approach for detecting the browser? Did a quick test with Safari 7 and 8 and it seems to work well: https://github.com/conditionizr/conditionizr Demo here: http://rafael.adm.br/css_browser_selector/

Not sure if we have/there is a preferred way of doing that.

**Comment by HenrikJoreteg** [comment]
It's a bit of a hack since it just detects safari and disables scrolling of the sidebar, but still, seems reasonable as a workaroun.
