### ISSUE TITLE
Add the following logos/links homepage

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersandjs.com#122]
These can all be added, with listed links:

Financial Times - https://twitter.com/callumlocke/status/552773119556190208
(I guess google image search for a logo)

Aviture - http://aviture.us.com/ 
![aviture-logo](https://cloud.githubusercontent.com/assets/67925/5675201/5e2e0d9e-976d-11e4-9cb8-c95442ef109d.png)

TeamWeek - http://blog.teamweek.com/2015/01/replacing-backbone-ampersandjs/ logos here: http://support.teamweek.com/press-kit

**Comment by JGAntunes** [comment]
Hey guys! We at @sinfo, an annual non-profit tech event entirely organized for students ([more info](www.sinfo.org)), are using AmpersandJS to build a web app that allows us to manage any kind of event (from speakers, to sponsors, communications, etc.) https://github.com/sinfo/eventdeck and we're loving it. We'll also build our public web app (for our attendees) with ampersand probably.

We were wondering if we could be listed as AmpersandJS users. Hope we qualify for it and, if so, here's are our logos.

Thank you!

https://www.dropbox.com/sh/8cgkwh12n3zhpwu/AACHhQsaeY7rQLE_rKL61GLwa?dl=0#/

**Comment by HenrikJoreteg** [comment]
@lynnandtonic can you add this one too? and link to http://sinfo.org/?

Also, mind asking Glenn in chat if we can list CAA too?

**Comment by lynnandtonic** [comment]
@HenrikJoreteg Yup! On it.

**Comment by jeffboyus** [comment]
You can add us as well.  http://www.pnnl.gov 

Image (eps file): [PNNL Logo](https://drive.google.com/file/d/0B51ZZrVYh_irZVplajNEM2pEaEU/view?usp=sharing)

**Comment by HenrikJoreteg** [comment]
oh yeah, thanks @jeffboyus I totally forgot.

**Comment by cdaringe** [comment]
We happily use it for some tools at @ the [Mind Research Network](http://www.mrn.org/). 

![logo](http://www.cdaringe.net/c/pub/img/logo_mind_research_network.png)
[logo](http://www.cdaringe.net/c/pub/img/logo_mind_research_network.png)

**Comment by JGAntunes** [comment]
Thank you very much @lynnandtonic @HenrikJoreteg  ;)
