### ISSUE TITLE
Be more inviting for new contributors

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersandjs.com#130]
Even though we have this great explanation of our bug triage process: http://ampersandjs.com/learn/bug-triage-process it's still unclear to many new people what our 'rules' are for contributing.

Perhaps a sentence or two could be added to the "How to contribute" section at the top of http://ampersandjs.com/contribute to invite people to that link, and encourage them to jump in if they see something they want to add?

**Comment by lynnandtonic** [comment]
@wraithgar Does this sound better?

![image](https://cloud.githubusercontent.com/assets/871315/7522018/40821f5a-f4a7-11e4-82dd-ef7210e52b3c.png)

**Comment by wraithgar** [comment]
Oh yes very nice thank you!

**Comment by lynnandtonic** [comment]
:+1:
