### ISSUE TITLE
gulp-browserify is no longer maintained

### ISSUE THREAD

**Issue by joerter** [AmpersandJS/ampersandjs.com#132]
This is a small change in the Learn section under [as part of grunt/gulp](http://ampersandjs.com/learn/npm-browserify-and-modules#as-part-of-gruntgulp)

Since [gulp-browserify](https://github.com/deepak1556/gulp-browserify) is no longer being maintained, and the GitHub README links to the gulp team's [recipes](https://github.com/gulpjs/gulp/tree/master/docs/recipes), I think it would be a good idea to remove the link to gulp-browserify and link to the recipes page instead.

I would be happy to submit a pull request for this!

**Comment by bear** [comment]
@joerter please do - documentation updates are very valuable!

create the PR and say in the comment that it fixes this issue and github will help close this once the PR is merged
