### ISSUE TITLE
Add WhatApp to users section of homepage

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersandjs.com#142]
I'd ask them, but i don't know who to ask. We know they're using it from the source code they send in their web app. I think we're ok to add them.

**Comment by lynnandtonic** [comment]
![image](https://cloud.githubusercontent.com/assets/871315/6353778/9347a80e-bc08-11e4-9889-3894d2f77669.png)

**Comment by HenrikJoreteg** [comment]
awesome, thanks Lynn
