### ISSUE TITLE
Would be cool to create a link in each section of "/docs" to "edit this" 

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersandjs.com#149]
We could have some sort of "suggest an edit" button/link on the "/docs" page that would drop link them right into the github editing view of the corresponding readme, this would make it suer quick and easy for people to submit doc fixes/improvements.

**Comment by HenrikJoreteg** [comment]
example target link: https://github.com/AmpersandJS/ampersand-model/edit/master/README.md

**Comment by HenrikJoreteg** [comment]
@lynnandtonic if you can think of a nice way to do this, visually. adding it would be trivial and it feels like a great way to get doc fixes and new contributors.

**Comment by lynnandtonic** [comment]
@HenrikJoreteg How does this feel?

![image](https://cloud.githubusercontent.com/assets/871315/7521482/ee551b14-f4a2-11e4-839c-be7e8fb34c55.png)

**Comment by HenrikJoreteg** [comment]
I like it!
