### ISSUE TITLE
Add our logo to the homepage

### ISSUE THREAD

**Issue by SilVdB** [AmpersandJS/ampersandjs.com#150]
We use Ampersand.js for https://app.neoScores.com and you can find our logo here:
![logo_neoscores-web](https://cloud.githubusercontent.com/assets/3997658/7278298/d26aa21e-e914-11e4-9286-86d7cf1c72a5.png)
.

**Comment by lynnandtonic** [comment]
Thank you so much, @SilVdB! :)
