### ISSUE TITLE
Events and derived properties doc bug, maybe

### ISSUE THREAD

**Issue by stuartlangridge** [AmpersandJS/ampersandjs.com#156]
From http://ampersandjs.com/learn/events

```
We can listen to it like this:
// we create a model
var model = new Model({name: 'audry', greetingType: 'short'});
// We can listen to a change to the derived property
model.on('change:greeting', function (model, val) { console.log('greeting is now: ', val) });
// Note that in our model definition the value of derived property will not change
// as long as the greeting type is `short`.
model.greetingType = 'short'; // callback runs and prints: "greeting is now: hi"
```

but... the `model` was created with `greetingType='short'`. So setting it explicitly here doesn't change it, and so that callback wouldn't run at that point, would it? Or have I misunderstood something?

**Comment by kamilogorek** [comment]
Hey @stuartlangridge, you're right, it should not run and it actually does not, docs are slightly off here.
In addition to that I just checked and we get callback run on first `name` change as well, which should not happen – http://requirebin.com/?gist=b4dff438efe129f507bc
Therefore it seems like a bug to me, but I'd like to ask someone to verify it @AmpersandJS/core-team 

What docs says right now:

``` js
// we create a model
var model = new Model({name: 'audry', greetingType: 'short'});

// We can listen to a change to the derived property
model.on('change:greeting', function (model, val) { console.log('greeting is now: ',    val) });

// Note that in our model definition the value of derived property will not change
// as long as the greeting type is `short`.
model.greetingType = 'short'; // callback runs and prints: "greeting is now: hi"

// so now if we change the name that callback would never fire
model.name = 'something else'; // callback doesn't run
model.name = 'you'; // still no

// but if we change the greeting type so the value is actually different, we'll get the event
model.greetingType = 'full'; // callback runs and prints: "greeting is now: hi you"
```

**Comment by HenrikJoreteg** [comment]
aww crap! Yes, thanks for finding this @stuartlangridge 

I've fixed the example and added some more clarifying comments. 

@kamilogorek your requirebin looks like a bug to me. An annoying one, however, because the only way to address it is to calculate all derived properties on init, to be able to determine whether they've changed. I'd rather not do this for performance reasons. I'd rather them be calculated/cached the first time they're accessed which is how it works currently.

In this gist, I simply access `model.greeting` in a console message and now it won't trigger on first change: http://requirebin.com/?gist=8b42c793289f42f57ed0

**Comment by kamilogorek** [comment]
@HenrikJoreteg fair enough. It shouldn't matter in a long run, so hopefully no one will report it soon :)

**Comment by HenrikJoreteg** [comment]
@kamilogorek i'm not necessarily saying it shouldn't be addressed, but i'm just not quite sure how to best go about it, given what i said above. I think the only way it could be done while respecting the performance aspect is to make it configurable as part of setting up the derived property. But that just sounds like adding a bunch of cruft for very little gain. /me shrugs.

**Comment by kamilogorek** [comment]
@HenrikJoreteg that are exactly my thoughts. But imo as long as we don't have a very specific usecase where it fails miserably and _have to_ be fixed, we can just postpone it in time for a while.
