### ISSUE TITLE
Add my logo to the homepage

### ISSUE THREAD

**Issue by alappe** [AmpersandJS/ampersandjs.com#159]
We happily use Ampersand.js for several client projects, in mobile hybrid apps and on user facing websites and you can find our logo as SVG here: https://dl.dropboxusercontent.com/u/1977824/zimmer7.svg

zimmer7.com

**Comment by lynnandtonic** [comment]
Thank you, @alappe! :+1:

**Comment by alappe** [comment]
Thanks for the fast response,

ah, font is not embedded… can you please replace it with?

![zimmer7](https://cloud.githubusercontent.com/assets/1357848/8727893/7d7e2f3a-2be2-11e5-9c91-34edc67fea37.png)

**Comment by lynnandtonic** [comment]
Ah, yup!

**Comment by lynnandtonic** [comment]
Should be good now! :)

**Comment by alappe** [comment]
Great, thanks!
