### ISSUE TITLE
Add Yola's logo to the homepage

### ISSUE THREAD

**Issue by kahnvex** [AmpersandJS/ampersandjs.com#167]
We use Ampersand.js for Yola's Sitebuilder and you can find our logo [here](http://i.imgur.com/cZybqAD.png?1).

**Comment by kahnvex** [comment]
We've also contributed back to the Ampersand.js community: https://github.com/yola/ampersand-multifield-view

**Comment by wraithgar** [comment]
The logo can link to your website too, what url should it link to?

**Comment by kahnvex** [comment]
https://yola.com

**Comment by lynnandtonic** [comment]
Thank you, @kahnjw! It's on the site now. :)
