### ISSUE TITLE
Add my logo to the homepage

### ISSUE THREAD

**Issue by rememberlenny** [AmpersandJS/ampersandjs.com#169]
We use Ampersand.js for https://federalist.18f.gov/ and you can find our logo ![](https://18f.gsa.gov/assets/images/logo-18f.png).

**Comment by rememberlenny** [comment]
More specifically @jeremiak

**Comment by lynnandtonic** [comment]
Thank you, @rememberlenny! :sparkles:

**Comment by jeremiak** [comment]
:tada: thanks @rememberlenny and @lynnandtonic
