### ISSUE TITLE
Add my logo to the homepage

### ISSUE THREAD

**Issue by sarumjanuch** [AmpersandJS/ampersandjs.com#172]
We use Ampersand.js for https://www.thirdlane.com/products/thirdlane-connect and you can find our logo https://www.thirdlane.com/sites/all/themes/thirdlaneseven/logo.png.

**Comment by lynnandtonic** [comment]
Hi @sarumjanuch! The Thirdlane logo is now on the Ampersand site. Thank you so much! <3

**Comment by sarumjanuch** [comment]
Thaks a lot Lynn. Have a good one.
