### ISSUE TITLE
Docs titles are a bit broken in some places:

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersandjs.com#31]
Seems that consecutive headers get collapsed onto one line because: `display: inline-block`:

![ampersand js - documentation 2014-06-26 14-13-43 2014-06-26 14-14-22](https://cloud.githubusercontent.com/assets/78225/3398724/ca8432ea-fd33-11e3-9641-afeab25358c1.png)

**Comment by HipsterBrown** [comment]
It looks like that might be the only issue. Should the "extend" title be below API Reference?

**Comment by latentflip** [comment]
Yeah it's cos there's no content between the two, and they're both inline-block. Everywhere else there's a short intro between API Reference and the first method.

**Comment by HipsterBrown** [comment]
So changing '.docs-content .anchor' to display: block will drop the extend below API Reference. In the process of making that change will submit a PR soon.
