### ISSUE TITLE
Scroll bar issue reported by twitter user: https://twitter.com/distilledhype/status/484283104736329728

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersandjs.com#44]
Could you look into this, Lynn? I'm guessing it's on windows, i'm not seeing it in Chrome/FF/Opera on my mac.

**Comment by lynnandtonic** [comment]
It shows up if you're using some external mice. I duplicated it by plugging in my drawing tablet.

I changed the overflow: scroll to overflow: auto and that fixed it. 

So the Learn page looks like this:
![image](https://cloud.githubusercontent.com/assets/871315/3460479/9eb03d92-0217-11e4-95fb-4ddda397681a.png)

While the Docs page still looks like this:
![image](https://cloud.githubusercontent.com/assets/871315/3460480/a9ce2662-0217-11e4-87a5-b8e5862af01c.png)
