### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by thefoxis** [AmpersandJS/ampersandjs.com#46]
Let's minify production CSS, so:
- [x] minify and rename `normalize.css` to `normalize.min.css`
- [ ] minify and rename `main.css` to `main.min.css`

**Comment by lynnandtonic** [comment]
I was having trouble getting main.styl to output main.min.css without having to rebuild for the changes to show up. I'm not sure why, so leaving as main.css for the moment.

**Comment by lynnandtonic** [comment]
Since we are thinking about having minification as part of the deploy process, I'm going to close this for now.
