### ISSUE TITLE
Standardize commenting

### ISSUE THREAD

**Issue by thefoxis** [AmpersandJS/ampersandjs.com#47]
Let's standardize commenting. Every file should have a header like this:

```
/*--------------------------------------------------------------------
*
* BASE
*
--------------------------------------------------------------------*/
```

And sections for elements in single stylus file should have the following header:

```
//- Section/Module Name
```

`main.styl` should have proper sectioning and annotations, [see here](https://github.com/andyet/blog.andyet.com/blob/master/public/styl/main.styl):

```
*--------------------------------------------------------------------
*
* project name
* optional version
*
* Designed and coded by @projectowner
* Maintained by &yet
* ❤︎ 
*
--------------------------------------------------------------------*/
```

The heart is optional ;)

**Comment by lynnandtonic** [comment]
Done!
