### ISSUE TITLE
Separate CSS and Stylus folders

### ISSUE THREAD

**Issue by thefoxis** [AmpersandJS/ampersandjs.com#48]
What I've started doing (and I think it should be standardized) is separating CSS and Stylus folders. So, in CSS folder we only have:
- `normalize.min.css`
- `main.min.css`

And `styl` folder in `static/` has all the stylus files and `main.styl`. For consistency sake we should also rename `static` to `public`, it's a bit confusing now - do you agree @HenrikJoreteg?

**Comment by lynnandtonic** [comment]
Moved stylus files and renamed static to public.

Having a bit of trouble renaming the main.css file to main.min.css, but I'll explain that in this issue: https://github.com/AmpersandJS/ampersandjs.com/issues/46

Closing this one.
