### ISSUE TITLE
Code highlighting is missing in a doc section

### ISSUE THREAD

**Issue by khalillechelt** [AmpersandJS/ampersandjs.com#65]
In this section of the docs: http://ampersandjs.com/docs#ampersand-view-render
the code highlighting is not working. When you look at the code you can see that the code is not wrapped with the correct classes. It rather looks like it has been wrapped with CSS classes for HTML code.

**Comment by khalillechelt** [comment]
Same goes for the code examples in http://ampersandjs.com/docs#ampersand-view-rendersubview

**Comment by khalillechelt** [comment]
Same goes for the code examples in http://ampersandjs.com/docs#ampersand-view-subviews

**Comment by HenrikJoreteg** [comment]
I believe this is resolved now. Was fighting with highlight.js for a bit. Ultimately the highlight markup should just be inserted by the build process. But, at least it seems to work now. (re-open if you disagree)
