### ISSUE TITLE
Which ES5 features are used?

### ISSUE THREAD

**Issue by callumlocke** [AmpersandJS/ampersandjs.com#72]
I think it's good for progress that you're only supporting IE9+.

But I'd like to know which ES5 features you use that require IE9+? Are there any that are fundamentally unpolyfillable in IE8? Or could I theoretically make a shim layer that would get (some if not all) Ampersand modules working in IE8?

**Comment by HenrikJoreteg** [comment]
The biggie is getters and setters via defineProperty.

It's possible that it could be worked around by always explicitly using .get() / .set() methods internally instead of direct assignments and then doing the same in your app.

The unshimmable part (at least as far as I know) is being able to get a `change` event on a direct assignment: `model.property = "thing"`

**Comment by callumlocke** [comment]
ok, that's interesting thanks.

I have to make lots of small front end apps, and sometimes they have to support IE8 (and this will be the case for another year or so). I'll try doing one as an experiment using only `.get()` and `.set()`, and see if it works in IE8.

**Comment by HenrikJoreteg** [comment]
I think you'll hit some issues with this internally though. All derived properties would explicitly have to be created as functions too, for example.

**Comment by HenrikJoreteg** [comment]
Arguably it could be done. So it'd be interesting to explore.

**Comment by callumlocke** [comment]
Cool I will explore. Closing this now as it's not really an issue except for me.

I am really happy about Ampersand btw. I've used Backbone for a long time but I always wished it had separate commonjs modules, derived properties, etc. I hope it gets a lot of traction.

**Comment by AoDev** [comment]
@callumlocke  Hi, as I'm myself interested in Ampersandjs working in IE8, I'd like to know the results of your IE8/Ampersandjs investigation.
