### ISSUE TITLE
We actually support other browsers besides IE9+

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersandjs.com#73]
The section of the site that says "Unapologetically supporting only IE9+." could probably be a little more explicit about what is supported so it doesn't sound like this is an IE-only framework.

**Comment by lynnandtonic** [comment]
I think I remember the previous version saying "Modern browsers by default" before the statement about IE9+. Is "Modern browsers by default" descriptive enough?

**Comment by latentflip** [comment]
@lynnandtonic you're right, the current text is: "Modern browsers by default. Unapologetically supporting only IE9+."

**Comment by latentflip** [comment]
Whether that's clear enough or not I dunno

**Comment by lynnandtonic** [comment]
Oh ha it still says that. I should have looked at the site, duh Lynn. :)

**Comment by HenrikJoreteg** [comment]
Worth clarifying for sure.

**Comment by lynnandtonic** [comment]
Should we include a list of the supported browsers? Like change "Unapologetically supporting only IE9+" to "Supports Chrome vX.X, Safari vX.X, IE9+."

Or we could eliminate the IE9+ sentence here and provide a "browser support" callout above or below the modules list on the right?

**Comment by wraithgar** [comment]
Ok now I guess I'm extra confused about what we support: https://ci.testling.com/ampersandjs/ampersand-state

(IE is failing)

**Comment by HenrikJoreteg** [comment]
Evergreen and ie 9 and newer should work just fine. Anything else is a bug. And really only stuff based on State should fail in IE8 just because defineProperty

**Comment by lynnandtonic** [comment]
This is clarified now with the new copy Henrik pushed, I think. Reopen if disagree!
