### ISSUE TITLE
Events documentation

### ISSUE THREAD

**Issue by quangv** [AmpersandJS/ampersandjs.com#75]
I think Events should be added to the documentation. The Backbone docs made it clear `Backbone.Events` is mixed into everything, and docs what it does clearly at the top.

It isn't 100% clear that things like `model.once` is supported in Ampersand.

If a person doesn't have Backbone experience wanted to use Ampersand, I doubt they will know the catalog of events that's available, along with methods like `on, once, listenTo ...`

**Comment by HenrikJoreteg** [comment]
This is a great point. +1

**Comment by wraithgar** [comment]
I also couldn't find listenTo on http://ampersandjs.com/docs anywhere.

**Comment by HenrikJoreteg** [comment]
this has long since been done, closing...
