### ISSUE TITLE
docs -- minor error in require statement

### ISSUE THREAD

**Issue by glenlovett** [AmpersandJS/ampersandjs.com#85]
On the first line of the file `client/some-other-file.js` in the guide http://ampersandjs.com/learn/transitioning-from-backbone

the require statement is
`var MyModel = require('./models/model');`
When it seems like it should be
`var MyModel = require('./models/my-model');`

This may have been intended to be implied, in which case never mind!

**Comment by wraithgar** [comment]
Thank you @glenlovett
