### ISSUE TITLE
Guide Typos

### ISSUE THREAD

**Issue by juddkussrow** [AmpersandJS/ampersandjs.com#89]
Hey Ampersand,

Been going through the guides and noticed few paltry errors.  Crowd sourcing the editing for y'all by letting no iteration of the experience go wasted...
- [x] quick-start-guide

> Install the ampersand command line **and running** by running this in a terminal:

... [should read](http://ampersandjs.com/learn/quick-start-guide) ...

> Install the ampersand command line by running this in a terminal:

---
- [x] npm-browserify-and-modules

> browserify helps you bundle your application that uses commonjs modules up into a single JavaScript file that you can use in your application in the browser.

... [is a run on sentence](http://ampersandjs.com/learn/npm-browserify-and-modules).

> Put together the flow of creating a very simple web application with these tools might look something like this:

... [needs a comma](http://ampersandjs.com/learn/npm-browserify-and-modules).

---
- [x] transitioning-from-backbone

> In addition, just by following a few conventions, you can even have those view still play nicely with other views.

[Views should be plural](http://ampersandjs.com/learn/transitioning-from-backbone).

---
- [x] state

> Well, as we said there's a huge amount of code that you write in a project really just describes and tracks relationships between values.

... [need to add a **that** in there](http://ampersandjs.com/learn/state).

> So, say you have a more "expensive" computation for model.

... [for a model](http://ampersandjs.com/learn/state)?  Next sentence is a bit of a run on too...

> Each state object you define will have and extend method on the constructor.

[Extra 'd' added to make that 'an' and 'and'](http://ampersandjs.com/learn/state).

> In addition, since it's a child that event propagates up.

[... a bit cumbersome](http://ampersandjs.com/learn/state). Might need another comma at the risk of splicing.

---

That's all I'm going to read today.  Maybe I'll come back and edit this when I continue if I find anything else.

Regards,
Judd

**Comment by kamilogorek** [comment]
We'd be greatful if you could send a PR with those changes :) Thanks for a notes!

**Comment by wraithgar** [comment]
PR not required though, if you find more go ahead and start a new issue for it though so we can get this one started. Cheers!

**Comment by wraithgar** [comment]
ok sorry for the edit spam, editing the OP didn't have a preview.

**Comment by juddkussrow** [comment]
I've already done a few commits on my fork. Might as well keep going. Good practice...
- Judd

**Comment by wraithgar** [comment]
If you're doing the work my PR will wait and potentially close w/o merging.

**Comment by wraithgar** [comment]
Ok all these ones are addressed, file a new issue or a PR for any others you find. Thanks for putting in the effort to help!
