### ISSUE TITLE
Add a "who uses Ampersand.js" section (or re-phrase the see it in action part)

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersandjs.com#93]
Or do something entirely different, up to you! But the point is, we got official go-ahead from Yahoo to list them as a user of ampersand. I'll forward you the email + logo, @lynnandtonic

**Comment by lynnandtonic** [comment]
I added the Yahoo! logo and moved the section up on the page. 

Should we provide a way for users to submit their company logo for this section? http://hapijs.com/ does this by sending them to an issue with instructions on how to do that. We could link to an issue or to a section in the README. Thoughts?

**Comment by jrmyio** [comment]
Maybe for the future it's interesting to know where exactly ampersand.js is being used. I understand it looks nice to have Yahoo on the list but it would be much more interesting to have some background information / use-case.

**Comment by lynnandtonic** [comment]
@ConneXNL That's a great idea! And I agree, that would be interesting. Once we have some more info or use-cases, we'll def share it (with permission of course). :)

**Comment by lynnandtonic** [comment]
I'm closing this issue, but I created https://github.com/AmpersandJS/ampersandjs.com/issues/95 to capture the thoughts about users submitting logos and/or use-case information.
