### ISSUE TITLE
Difference between State and Model is fuzzy.

### ISSUE THREAD

**Issue by sethlivingston** [AmpersandJS/ampersandjs.com#94]
The guide never differentiates between ampersand-state and ampersand-model. I think this could be fixed by:
1. Pointing out that ampersand-state is the base for ampersand-model, as stated in the ampersand-state README.
2. Being careful with the word model in the "Understanding State" section, especially before the difference between the two has been pointed out.

I'm happy to submit some PRs if you feel this issue is legit.

**Comment by wraithgar** [comment]
We're addressing the second point at least somewhat here https://github.com/AmpersandJS/ampersand-state/pull/59

**Comment by ivan-kleshnin** [comment]
I think, guys, that we have a problem with naming part.
We have two inheritance chains:

```
State > Model
Collection > RestCollection
```

So "model" is a "state" out of inheritance. But "state" is also "model" out of MVC.
I bet that state declarations will be put under `models` folder or in `models.js` file. So we have logic depency lock here. 

Second problem is that `Rest` suffix. `Model` class implements REST interface and is named **without** any suffix, while RestCollection implements REST interface and is named **with** suffix.... It definitely seems confusing. 

Maybe this version will make more sense:

```
Model > RestModel
Collection > RestCollection
```

**Comment by kamilogorek** [comment]
Issue here is that most of the people will assume that there's already some kind of communication layer in a pure `Model` if we'd ever rename `state`, where it won't be unless you mix it yourself or use `RestModel`. This might be misleading.

**Comment by e2jk** [comment]
FWIW: viewpoint of somebody new to MVC in JavaScript (my experience lies with Django models), I don't expect Model to have communication included.
The word State makes me feel like this object tracks the "status" of other objects, not necessarily the "content" of that object.

Use this with a grain of salt, as I'm just getting started with Ampersand.js.

**Comment by prust** [comment]
FWIW, I have to agree with @ivan-kleshnin & @e2jk here.

Even though my team and I have been coding heavily in Backbone for years, splitting `Backbone.Model` into `Model > RestModel` makes a lot more sense to me than `State > Model`. It's not a huge deal and it would mean a lot of documentation changes, but the introduction of `State` concept/vocabulary, when `Model` is the industry standard for the concept, adds a little more sand in the gears of ampersand adoption.

**Comment by kamilogorek** [comment]
@sethlivingston you could've waited for 10 years... such missed opportunity 😄

**Comment by sethlivingston** [comment]
I should've done that, @kamilogorek! Too funny 😆
